# H2 in-memory

spring.datasource.driver-class-name=org.h2.Driver

# JPA/Hibernate

spring.jpa.properties.hibernate.format_sql=true
spring.datasource.url=jdbc:h2:mem:librarydb
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=none
spring.sql.init.mode=always

spring.sql.init.schema-locations=classpath:schema.sql
spring.sql.init.data-locations=classpath:data.sql

# Web server
server.port=8080

# H2 Console (optional, for debugging)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JWT Configuration
jwt.secret=mySecretKeyForJWTTokenGenerationAndValidationMustBeAtLeast256BitsLong
jwt.expiration=86400000